{% set version = "2.3" %}

{% set PYTHON = PYTHON | default("$PYTHON") %}

package:
  name: collatex-python
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/c/collatex/collatex-{{ version }}.tar.gz
  sha256: ae61abf9d1093c894544096bf8bd23f87d9409e9ff3c3052b31cffff190f9ad3

build:
  number: 1
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - networkx
    - prettytable
    - python >={{ python_min }}
    - python-levenshtein

test:
  imports:
    - collatex
  commands:
    - pip check
  requires:
    - pip

outputs:
  - name: collatex-python

  - name: collatex-python-with-jupyter
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage("collatex-python", max_pin="x.x.x") }}
        - ipython
        - python-graphviz
    test:
      source_files:
        - tests
      imports:
        - collatex
      commands:
        - pip check
        - pytest -vv --cov=collatex --cov-report=term-missing:skip-covered --no-cov-on-fail --cov-fail-under=54 -k 'not (duplicated_tokens_in_witness2 or export_alignment_table_as_tei)'
      requires:
        - pip
        - pytest-cov
        - python {{ python_min }}

about:
  home: https://collatex.net
  summary: CollateX is a collation tool.
  license: GPL-3.0-or-later
  license_file: LICENSE
  dev_url: https://github.com/interedition/collatex

extra:
  feedstock-name: collatex-python
  recipe-maintainers:
    - bollwyvl
